<!-- This script contains code to build a web page with a form. It includes a PHP code to dynamically generate the html to display one checkbox for each of the toys currently held in the NTL_toys database table within the form. The user can select one or more toys that they are interested in ordering by clicking the checkboxes. Use the browser to look at the structure of the html generated by the php code.

You MUST NOT in any way change the php code provided OR the code within the FORM tags.

You MAY add Javascript for task 4.
You MAY modify the page to add your own navigation menu and link to your own stylesheet using additional html or php. However, please note that styling will not be marked for this assignment. -->

<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Order Toys</title>
</head>

<body>
	<h1>Order Toys</h1>
	<nav>
		<ul>
			<li><a href="index.html">Home</a></li>
			<li><a href="toyQuery.php">View Toy List</a></li>
			<li><a href="orderToysForm.php">Order Toy(s)</a></li>
			<li><a href="credits.html">Credits</a></li>
			<li><a href="loginForm.html">Login</a></li>
		</ul>
	</nav>

	<form id="orderForm" action="javascript:alert('form submitted');" method="get">
		<section id="orderToys">
			<h2>Select Toys</h2>
			<?php
			try {
				// include the file with the function for the database connection
				require_once('functions.php');
				// get database connection
				$dbConn = getConnection();
				$sqlToys = 'SELECT toyID, toyName, catDesc, manName, toyPrice FROM NTL_toys t INNER JOIN NTL_category c ON t.catID = c.catID INNER JOIN NTL_manufacturer m ON t.manID = m.manID ORDER BY toyName';

				// execute the query
				$rsToys = $dbConn->query($sqlToys);

				while ($toy = $rsToys->fetchObject()) {
					$toyName = $toy->toyName;
					echo "\t<div class='item'>
				<span class='toyName'>" . filter_var($toyName, FILTER_SANITIZE_SPECIAL_CHARS) . "</span>
	            <span class='catDesc'>{$toy->catDesc}</span>
	         	<span class='manName'>{$toy->manName}</span>
	            <span class='toyPrice'>{$toy->toyPrice}</span>
	            <span class='chosen'><input type='checkbox' name='toy[]' value='{$toy->toyID}' data-price='{$toy->toyPrice}'></span>
	      		</div>\n";
				}
			} catch (Exception $e) {
				echo "Problem " . $e->getMessage();
			}
			?>
		</section>
		<section id="collection">
			<h2>Collection method</h2>
			<p>Please select whether you want your chosen toy(s) to be delivered to your home address (a charge applies for this) or whether you want to collect them yourself.</p>
			<p>
				Home address - &pound;8.99 <input type="radio" name="deliveryType" value="home" data-price="8.99" checked>&nbsp; | &nbsp;
				Collect from shop - no charge <input type="radio" name="deliveryType" value="shop" data-price="0">
			</p>
		</section>
		<section id="checkCost">
			<h2>Total cost</h2>
			Total <input type="text" name="total" size="10" readonly>
		</section>
		<section id="placeOrder">
			<h2>Place Order</h2>
			<h3>Your details</h3>
			<div id="retCustDetails" class="custDetails">
				Forename <input type="text" name="forename">
				Surname <input type="text" name="surname">
			</div>
			<p style="color: #FF0000; font-weight: bold;" id='termsText'>I have read and agree to the terms and conditions
				<input type="checkbox" name="termsChkbx">
			</p>
			<p><input type="submit" name="submit" value="Book now!" disabled></p>
		</section>
	</form>
	<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for task 4 of the assignment -->
	<script>
		window.addEventListener('load', function() {
			"use strict";

			const l_form = document.getElementById('orderForm');

			l_form.addEventListener("change", calculateTotal);
			l_form.submit.addEventListener("click", checkSubmit);
			//l_form.retCustDetails.addEventListener("click", checkDetails);
			//l_form.submit.addEventListener("click", checkForm);
			l_form.termsChkbx.addEventListener("click", checkTerms);

			function calculateTotal() {
				let l_total = 0;

				const l_adverts = l_form.querySelectorAll('div.item');
				const l_advertsCount = l_adverts.length;


				for (let t_i = 0; t_i < l_advertsCount; t_i++) {
					const t_advert = l_adverts[t_i];
					const t_checkbox = t_advert.querySelector('input[data-price][type=checkbox]');

					if (t_checkbox.checked) {
						l_total = l_total + parseFloat(t_checkbox.dataset.price);
					}

				}
				l_form.total.value = l_total;
				l_grandTotal = l_grandTotal = parseFloat(l_total);
				let l_shippingValue = document.querySelector('input[name="deliveryType"]:checked');
				let l_shippingCost = 0;
				if (l_shippingValue != null) {
					l_shippingCost = parseFloat(l_shippingValue.dataset.price);
				}

				l_grandTotal = l_grandTotal + l_shippingCost;

			}
			/* function checkedBox() {
				const toyCheck = document.getElementById('orderToys').checked;
				toyCheck.CheckValue = checkedBox();
				const checkedToys = toyCheck.querySelectorAll('input[data-price][type=checkbox]');

				const toys_Count = checkedToys.length;

				for (u_i = 0, 1 = toys_Count.length; u_i < 1; u_i++) {
					const u_box = checkedToys[u_i];
					if (u_box.checked) {
						toyCheck.setCustomValidity("Please choose a toy");
					} else {
						toyCheck.setCustomValidity("");
					}
				}
			} */

			function checkSubmit() {
				if (l_form.forename.validity.typeMismatch) {
					l_form.submit.disabled = true;
				}

				if (l_form.surnname.validity.typeMismatch) {
					l_form.submit.disabled = true;
				} else {
					l_form.submit.disabled = false;
				}
			}

			function checkTerms() {
				if (l_form.termsChkbx.checked) {
					document.getElementById("termsText").style.fontWeight = "normal";
					document.getElementById("termsText").style.color = "black";
					l_form.submit.disabled = false;
				} else {
					document.getElementById("termsText").style.fontWeight = "bold";
					document.getElementById("termsText").style.color = "red";
					l_form.submit.disabled = true;
				}
			}
			//  validation
			/*	function checkForm(_evt) {
					alert("checking form");
					_evt.preventDefault();
				} //checkForm() */


		});
	</script>

</body>

</html>